Evidently library has used the method from scipy library to compare two datasets for their distribution.

Null: Two datset are from same distribution

Alterate: Two dataset are not from same distribution

if p>=0.05 :
    We have sufficent proof that null hypothesis is True
else:
    We don't have sufficient proof that null hypothesis is True

In [2]:
from scipy.stats import ks_2samp

In [3]:
import numpy as np

# First Example

In [5]:
arr1 = np.arange(10)
arr2=np.arange(10)

In [17]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
res = ks_2samp(arr1,arr2)

In [7]:
res

KstestResult(statistic=0.0, pvalue=1.0)

In [20]:
# Therefore, the two datasets are from the same distribution.
round(res.pvalue)

1

# Second Example

In [10]:
arr1 = np.arange(10)
arr2=np.arange(10,20)

In [12]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
# We are getting very small value, so the two datasets are not from the similar distribution.
res= ks_2samp(arr1,arr2)
res.pvalue

1.0825088224469026e-05

In [18]:
round(res.pvalue)

0

In [17]:
round(res.pvalue,3)

0.0